apiVersion: v1
kind: Secret
metadata:
  name: test-gateway-config
stringData:
  api_token: "an_api_token"
  domain: "example.com"
  email: "my@email.com"
  account_id: "6ea2bf2691e109ad8c43e1a64e6a907c"