---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - gateway.networking.k8s.io.adamland.xyz
  resources:
  - gatewayclasses
  - gateways
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.networking.k8s.io.adamland.xyz
  resources:
  - gatewayclasses/finalizers
  - gateways/finalizers
  verbs:
  - update
- apiGroups:
  - gateway.networking.k8s.io.adamland.xyz
  resources:
  - gatewayclasses/status
  - gateways/status
  verbs:
  - get
  - patch
  - update
