apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: cloudflare-gateway-controller-system
spec:
  template:
    spec:
      containers:
        - name: controller
          imagePullPolicy: Never
          image: cloudflare-gateway-controller:latest
